deviceModeInit.js
=> Shopify Device Mode Issue 

deviceModeInit.js
Enabling following support
- userId tracking if available during init
- tracking email, firstName, lastName during login
- tracking email, firstName, lastName during registration
> Fix [#1]()
=> Enabled user identifier tracking for shopify device mode

deviceModeInit.js
This PR adds the feature of reading and writing cookies, the primary use case for this feature is to reduce the number of identify calls made from client side also using the cookie_token as secondary identifier for the user activity tracking.
> Fix [#1]()
=> bugfix(core): Fix to identity resolution issue

deviceModeInit.js, router.js
With this pull request we are adding support for identity stitching.
> Fix [#1]()
=> feat: identity stitching

deviceModeInit.js
>  We will be storing the cart attributes in cookies.
> Fix [#1]()
=> feat: storing cart attributes as cookie

deviceModeInit.js, package-lock.json
> Sending Rudder Identifier at a regular time-period irrespective of the user activity.
> Fix [#1]()
=> feat: fire Rudder Identifier Periodically

deviceModeInit.js, router.js
> Provide user  an option to disable client-side identify events through sourceConfig Api
> Fix [#1]()
=> feat: skip client side identify calls

deviceModeInit.js
Following are the features/enhancements :
1. Updating the product list viewed event to add support for the scroll-based function calling feature.
2. Console Statements type updated
3. Sending variant as an object of current visible variant instead of sending all the variants in form of array of objects.
> Fix [#1]()
=> feat: update product list viewed event call

deviceModeInit.js
> This PR contains changes to change the data structure of variant from object to an array of object.
In addition to this there needed some changes in the flow of How and when we add Product Event Listeners to track `Product Clicked` Events. So this incorporates that as well
> Fix [#1]()
=> chore: reverting the data structure for variant from array to object

deviceModeInit.js
We are doing cart update before sending rudderIdentifier due which first cart_update is not getting stitched
=> fix: sending rudderIdentifier before cart update cal

deviceModeInit.js
=> revert: chore: send rudderIdentifier before cart update

.github/workflows/prod-deploy.yml
> fixing ci/cd file name
> Fix [#1]()
=> fix: ci/cd file name

.github/workflows/build-and-push-docker-image.yml
=> fix: docker file name

.github/workflows/build-and-push-docker-image.yml, .github/workflows/prod-deploy.yml
=> fix: prod deploy condition

.github/workflows/build-and-push-docker-image.yml, .github/workflows/prod-deploy.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull hotfix-release/v1.2.2 into main

.github/workflows/prod-deploy.yml
=> feat(workflow): changing the format

.github/workflows/prod-deploy.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull release/v1.3.0 into main

.github/workflows/prod-deploy.yml
=> feat: clean up prod deploy workflow

.github/workflows/prod-deploy.yml
=> fix: prod deploy workflow job

.github/workflows/prod-deploy.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull release/v1.4.1 into main

.github/workflows/build-and-push-docker-image.yml, .github/workflows/prod-deploy.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull release/v1.4.2 into main

.github/workflows/prod-deploy.yml
=> fix: docker image tag

.github/workflows/prod-deploy.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull release/v1.4.3 into main

.github/workflows/build-and-push-docker-image.yml, .github/workflows/draft-new-release.yml, .github/workflows/housekeeping.yml, .github/workflows/prod-deploy.yml, .github/workflows/publish-new-release.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull release/v1.4.4 into main

.github/workflows/build-and-push-docker-image.yml, .github/workflows/prod-deploy.yml
=> fix: formatting files

.github/workflows/build-and-push-docker-image.yml, .github/workflows/prod-deploy.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull hotfix-release/v1.4.5 into main

.github/workflows/publish-new-release.yml
=> fix: the release owners

.github/workflows/publish-new-release.yml, CHANGELOG.md, package-lock.json, package.json
=> chore(release): pull hotfix-release/v1.4.6 into main

CHANGELOG.md, Dockerfile, package-lock.json, package.json
=> chore(release): pull release/v1.4.7 into main

Dockerfile, package-lock.json, package.json
> Resolves INT-940
Update node version to minimize vulnerabilities
> Fix [#1]()
=> chore: update node version

.github/workflows/draft-new-release.yml, .github/workflows/publish-new-release.yml, CHANGELOG.md, Dockerfile, package-lock.json, package.json
=> chore(release): pull release/v1.4.8 into main

.github/workflows/build-and-push-docker-image.yml, .github/workflows/prod-deploy.yml
We are updating the authentication method to GitHub token from GitHub password.
> Fix [#1]()
=> chore: update GitHub token

.github/workflows/prod-deploy.yml
Hub is deprecated so updating the pr creation command on workflow.
=> chore: update publish command in workflow

.github/workflows/release-please.yml
- Release version was not mentioned correctly in release-please GHA
- Removed release-please branch condition
Resolves INT-1411
N/A
N/A
N/A
N/A
<hr>
=> fix: release version and deletion of release-please branch post release

.github/workflows/release-please.yml
Reverts rudderlabs/rudder-shopify-tracker#112
=> Revert "fix: release version and deletion of release-please branch post release"

.github/workflows/release-please.yml
Reverts rudderlabs/rudder-shopify-tracker#110
=> Revert "fix: release deployment"

.github/workflows/build-pr-artifacts.yml, .github/workflows/draft-new-release.yml, CHANGELOG.md, Dockerfile, package-lock.json, package.json
=> chore(release): pull release/v1.4.10 into main

package-lock.json, package.json
Upgrade axios to v1.6.4 to resolve snyk vulnerabilities
Resolves INT-1949
N/A
N/A
N/A
N/A
<hr>
=> chore: upgrade axios to v1.6.4 to resolve snyk vulnerabilities

package-lock.json, package.json
Override package version for 3 packages to resolve vulnerabilities
Resolves INT-1988
N/A
N/A
N/A
N/A
<hr>
=> chore: override dependent package versions to reduce vulnerabilities

.github/workflows/build-and-push-docker-image.yml, .github/workflows/build-pr-artifacts.yml, .github/workflows/commitlint.yml, .github/workflows/draft-new-release.yml, .github/workflows/prod-deploy.yml, .github/workflows/publish-new-release.yml, .github/workflows/tests-code-coverage.yml
In GitHub workflows wherever checkout action is used, now fetch and checkout the pull request head commit instead of merge commit
Resolves INT-2190
N/A
N/A
N/A
N/A
<hr>
=> chore: checkout the pull request head commit instead of merge commit in GHAs

.github/workflows/build-pr-artifacts.yml
Add a step to validate branch name in Build Artifacts for PRs workflow
Resolves INT-2122
N/A
N/A
N/A
N/A
<hr>
=> chore: add a step to validate branch name in Build Artifacts for PRs workflow

package-lock.json, src/router.js
currently shopify tracker script is not sanitizing query params so we are doing that now.
Resolves INT-2571
N/A
N/A
N/A
N/A
<hr>
=> feat: add query params sanitization

.github/workflows/build-pr-artifacts.yml, .github/workflows/publish-new-release.yml, .github/workflows/tests-code-coverage.yml, package-lock.json, src/router.js
=> chore: rebase develop

.github/workflows/build-pr-artifacts.yml
Write a brief explainer on your code changes.
Resolves INT-XXX
N/A
N/A
N/A
N/A
<hr>
=> chore: fix artifact workflow

commitlnt.config.js, package-lock.json, package.json, src/deviceModeInit.js, src/loadingCode.js, src/router.js
remove redundant https
Resolves INT-XXX
N/A
N/A
N/A
N/A
<hr>
=> chore: remove redundant https

CHANGELOG.md, commitlnt.config.js, package-lock.json, package.json, src/deviceModeInit.js, src/loadingCode.js, src/router.js
=> chore(release): pull release/v1.5.1 into main

CHANGELOG.md, package-lock.json, package.json, src/deviceModeInit.js, src/loadingCode.js, src/router.js
=> chore(release): pull release/v1.5.2 into main

.github/workflows/publish-new-release.yml, .github/workflows/tests-code-coverage.yml
Write a brief explainer on your code changes.
Resolves INT-XXX
N/A
N/A
N/A
N/A
<hr>
=> chore: pull main to develop

package-lock.json, package.json
Upgrade axios version to 1.6.4 from 1.7.5 to resolve XSS Vulnerability.
There are no breaking changes in the package itself.
Resolves INT-2980
Part of vulnerability fixes in all repositories owned by integrations team
No
No
No
No
<hr>
=> chore: upgrade axios version with no code change

CHANGELOG.md, package-lock.json, package.json, src/logger.js, src/router.js
=> chore(release): pull release/v1.6.0 into main

src/logger.js
=> feat: remove ip from log

CHANGELOG.md, package-lock.json, package.json, src/logger.js
=> chore(release): pull release/v1.7.0 into main

CHANGELOG.md, package-lock.json, package.json, src/deviceModeInit.js
=> chore(release): pull release/v1.7.1 into main

.npmrc, package.json
Remove prepare script for husky init
Resolves INT-XXX
N/A
N/A
N/A
N/A
<hr>
=> chore: remove prepare script
